Repository bounswe/2021SpringGroup5, pull requests merged in 2021-06, with the labels that each got.

#131 Gozdebranch
  practice-app/group5_api/group5_api/.env
  practice-app/group5_api/group5_api/settings.py
  practice-app/group5_api/home/templates/home/home.html
  practice-app/group5_api/home/urls.py
  practice-app/group5_api/home/views.py
  practice-app/group5_api/weatherCondition/__init__.py
  practice-app/group5_api/weatherCondition/admin.py
  practice-app/group5_api/weatherCondition/apps.py
  practice-app/group5_api/weatherCondition/migrations/0001_initial.py
  practice-app/group5_api/weatherCondition/migrations/__init__.py
  practice-app/group5_api/weatherCondition/models.py
  practice-app/group5_api/weatherCondition/serializer.py
  practice-app/group5_api/weatherCondition/templates/weatherCondition/base.html
  practice-app/group5_api/weatherCondition/templates/weatherCondition/weatherConditions.html
  practice-app/group5_api/weatherCondition/tests.py
  practice-app/group5_api/weatherCondition/urls.py
  practice-app/group5_api/weatherCondition/views.py
  practice-app/group5_api/weatherCondition/weatherCondition.md
Labels: development, medium

#168 Home
  practice-app/group5_api/home/templates/home/home.html
  practice-app/group5_api/weatherCondition/migrations/0001_initial.py
Labels: development

#154 Added API named nbaStats and related html files
  practice-app/group5_api/group5_api/settings.py
  practice-app/group5_api/home/templates/home/home.html
  practice-app/group5_api/home/urls.py
  practice-app/group5_api/nbaStats/__init__.py
  practice-app/group5_api/nbaStats/__pycache__/__init__.cpython-38.pyc
  practice-app/group5_api/nbaStats/__pycache__/models.cpython-38.pyc
  practice-app/group5_api/nbaStats/__pycache__/urls.cpython-38.pyc
  practice-app/group5_api/nbaStats/__pycache__/views.cpython-38.pyc
  practice-app/group5_api/nbaStats/admin.py
  practice-app/group5_api/nbaStats/apps.py
  practice-app/group5_api/nbaStats/migrations/__init__.py
  practice-app/group5_api/nbaStats/models.py
  practice-app/group5_api/nbaStats/templates/base.html
  practice-app/group5_api/nbaStats/templates/player.html
  practice-app/group5_api/nbaStats/tests.py
  practice-app/group5_api/nbaStats/urls.py
  practice-app/group5_api/nbaStats/views.py
Labels: development, medium

#176 Atasoybranch
  .DS_Store
  .gitignore.md
  practice-app/.DS_Store
  practice-app/group5_api/.DS_Store
  practice-app/group5_api/group5_api/settings.py
  practice-app/group5_api/home/templates/home/home.html
  practice-app/group5_api/home/urls.py
  practice-app/group5_api/home/views.py
  practice-app/group5_api/requirements.txt
  practice-app/group5_api/sport_relation/README.md
  practice-app/group5_api/sport_relation/__init__.py
  practice-app/group5_api/sport_relation/admin.py
  practice-app/group5_api/sport_relation/apps.py
  practice-app/group5_api/sport_relation/migrations/0001_initial.py
  practice-app/group5_api/sport_relation/migrations/__init__.py
  practice-app/group5_api/sport_relation/models.py
  practice-app/group5_api/sport_relation/serializers.py
  practice-app/group5_api/sport_relation/templates/base.html
  practice-app/group5_api/sport_relation/templates/sport_relation/index.html
  practice-app/group5_api/sport_relation/templates/sport_relation/similar.html
  practice-app/group5_api/sport_relation/templates/sport_relation/suggest.html
  practice-app/group5_api/sport_relation/tests.py
  practice-app/group5_api/sport_relation/urls.py
  practice-app/group5_api/sport_relation/views.py
Labels: development, medium

#167 Berkaybranch
  practice-app/.gitignore
  practice-app/airqualityapi/__init__.py
  practice-app/airqualityapi/admin.py
  practice-app/airqualityapi/apps.py
  practice-app/airqualityapi/migrations/0001_initial.py
  practice-app/airqualityapi/migrations/__init__.py
  practice-app/airqualityapi/models.py
  practice-app/airqualityapi/serializers.py
  practice-app/airqualityapi/templates/airqualityapi/base.html
  practice-app/airqualityapi/tests.py
  practice-app/airqualityapi/urls.py
  practice-app/airqualityapi/views.py
  practice-app/group5_api/.env
  practice-app/group5_api/__init__.py
  practice-app/group5_api/asgi.py
  practice-app/group5_api/settings.py
  practice-app/group5_api/urls.py
  practice-app/group5_api/wsgi.py
  practice-app/home/__init__.py
  practice-app/home/admin.py
  practice-app/home/apps.py
  practice-app/home/migrations/__init__.py
  practice-app/home/models.py
  practice-app/home/templates/home/home.html
  practice-app/home/tests.py
  practice-app/home/urls.py
  practice-app/home/views.py
  practice-app/manage.py
  practice-app/requirements.txt
Labels: development

#211 Docker
  .gitignore
  practice-app/group5_api/.env
  practice-app/group5_api/docker-compose.yml
  practice-app/group5_api/group5_api/.env
Labels: development, urgent
